typography_spectrum: 0.599771139677614
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5042374422773719
  lightness: 0.901429993333295
  saturation: 0.9384978443849832
  rhythmicContrast: 0.3123905116226524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.19327274477109313
analytics:
  google: null
  facebook: null
  twitter: null
name: Sales Optimiser
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me...
    url: www.forestgrass.net
    type: external
favicon: null
title: Synthetic Lawn
description: '"spot the difference"'
purpose: []
