typography_spectrum: 0.7752739035058767
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.11187081295065582
  lightness: 0.08845173614099622
  saturation: 0.6029297930654138
  rhythmicContrast: 0.6815277093555778
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07209459412842989
analytics:
  google: null
  facebook: null
  twitter: null
name: Sales Optimiser
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me...
    url: www.forestgrass.net
    type: external
favicon: null
title: Synthetic Lawn
description: '"spot the difference"'
purpose: []
